### PR TITLE
Fix crash in iOs Safari (tested on iOs 8.4.1)

### PR DESCRIPTION
**Pull request by Vasyl-Kobyletskiy**
In mobile Safari Number has no parseFloat method

### CODE REVIEW

**Comment by mikkoh** [comment]
@Vasyl-Kobyletskiy thanks for the PR.

I just noticed a few things.

If you change the require statements to:

https://github.com/Jam3/css-transform-to-mat4/pull/1/commits/6c848d7ccc31d836437f48db4c1ebb3b8243bda1#diff-168726dbe96b3ce427e7fedce31bb0bcL1

If you change it to be the way it exists in this PR it would mean that all of `gl-mat4` would be bundled and not just the required functions from the `gl-mat4` module. It would be nice to make this module just require what's needed so that file size stays low.

Out of curiousity why did you use a github dep vs the npm dep?

**Comment by Vasyl-Kobyletskiy** [comment]
11.05.2016, 20:35, "Mikko Haapoja" notifications@github.com:@Vasyl-Kobyletskiy thanks for the PR.I just noticed a few things.If you change the require statements to:6c848d7#diff-168726dbe96b3ce427e7fedce31bb0bcL1If you change it to be the way it exists in this PR it would mean that all of gl-mat4 would be bundled and not just the required functions from the gl-mat4 module. It would be nice to make this module just require what's needed so that file size stays low.Out of curiousity why did you use a github dep vs the npm dep?—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub Good afternoon! Thank you for repling our request.The reason why we are using github deps is that for example gl-mat4 has no bower.json in it's structure, so bower can't install it.And one small question: what about status of issue in iOs?

**Comment by mikkoh** [comment]
@Vasyl-Kobyletskiy In `master` I've swapped `Number.parseFloat` to be `parseFloat`. I will not merge in this pull requests as I don't think it's wise to use git dependencies over npm dependencies. And generally speaking I only plan to support npm over bower.

**Comment by Vasyl-Kobyletskiy** [comment]
12.05.2016, 18:27, "Mikko Haapoja" notifications@github.com:@Vasyl-Kobyletskiy In master I've swapped Number.parseFloat to be parseFloat. I will not merge in this pull requests as I don't think it's wise to use git dependencies over npm dependencies. And generally speaking I only plan to support npm over bower.—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHubJust swapping Number.parseFloat to be parseFloat in master is what we where wanted. Thank you for supporting in fixing this issue.

**Pull request closed without merging**
